// app/components/styles.ts - Ultra Premium Redesign (Creme/Bege Edition)

const accentColor = '#10b981'; // Emerald Green
const accentGlow = 'rgba(16, 185, 129, 0.15)';

// 🎨 NOVAS CORES - Fundo Creme/Bege
const bgPrimary = '#f5f0eb'; // Creme principal
const bgSecondary = '#faf7f2'; // Creme mais claro
const bgCard = '#ffffff'; // Branco para cards
const bgDark = '#2d2a24'; // Escuro para textos
const cardBorder = 'rgba(0, 0, 0, 0.08)';
const textPrimary = '#1a1a1a';
const textSecondary = '#6b5f55'; // Marrom acinzentado

export const styles: any = {
  // ========== CONTAINER PRINCIPAL ==========
  appContainer: {
    display: 'flex',
    minHeight: '100vh',
    background: `linear-gradient(135deg, ${bgPrimary} 0%, ${bgSecondary} 100%)`,
    color: textPrimary,
    fontFamily: '"Inter", "Segoe UI", sans-serif',
  },

  // ========== SIDEBAR ==========
  sidebar: {
    background: 'linear-gradient(180deg, #2d2a24 0%, #1a1714 100%)',
    color: 'white',
    display: 'flex',
    flexDirection: 'column',
    transition: 'width 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    position: 'fixed',
    height: '100vh',
    zIndex: 100,
    borderRight: `1px solid rgba(255, 255, 255, 0.08)`,
    boxShadow: '10px 0 30px rgba(0,0,0,0.2)',
    overflowX: 'hidden',
  },
  sidebarHeader: {
    padding: '32px 24px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: `1px solid rgba(255, 255, 255, 0.08)`,
  },
  logo: { display: 'flex', alignItems: 'center', gap: '16px' },
  logoIcon: {
    fontSize: '24px',
    color: accentColor,
    filter: `drop-shadow(0 0 8px ${accentGlow})`,
  },
  logoText: {
    fontSize: '20px',
    fontWeight: 800,
    letterSpacing: '2px',
    textTransform: 'uppercase',
    background: `linear-gradient(135deg, ${accentColor} 0%, #34d399 100%)`,
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  toggleBtn: {
    background: 'rgba(255,255,255,0.05)',
    border: `1px solid rgba(255,255,255,0.08)`,
    color: '#94a3b8',
    cursor: 'pointer',
    padding: '10px',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sidebarNav: {
    flex: 1,
    padding: '24px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    overflowY: 'auto',
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    padding: '14px 18px',
    background: 'transparent',
    border: '1px solid transparent',
    color: '#94a3b8',
    cursor: 'pointer',
    borderRadius: '16px',
    fontSize: '14px',
    fontWeight: 600,
    width: '100%',
    textAlign: 'left',
    transition: 'all 0.3s ease',
  },
  navItemActive: {
    background: 'rgba(16, 185, 129, 0.15)',
    color: accentColor,
    border: `1px solid rgba(16, 185, 129, 0.2)`,
    boxShadow: `0 4px 15px rgba(16, 185, 129, 0.1)`,
  },
  navIcon: { width: '20px', fontSize: '18px' },
  navLabel: { whiteSpace: 'nowrap' },
  sidebarFooter: {
    padding: '24px 16px',
    borderTop: `1px solid rgba(255, 255, 255, 0.08)`,
  },
  logoutBtnSidebar: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    padding: '14px 18px',
    background: 'rgba(239, 68, 68, 0.1)',
    border: '1px solid rgba(239, 68, 68, 0.15)',
    color: '#ef4444',
    cursor: 'pointer',
    borderRadius: '16px',
    width: '100%',
    fontSize: '14px',
    fontWeight: 600,
    transition: 'all 0.3s ease',
  },

  // ========== MAIN CONTENT ==========
  mainContent: {
    flex: 1,
    transition: 'margin-left 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    padding: '40px 48px',
  },
  topBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '40px',
    paddingBottom: '24px',
    borderBottom: `2px solid ${cardBorder}`,
  },
  pageTitle: {
    fontSize: '32px',
    fontWeight: 800,
    color: textPrimary,
    marginBottom: '8px',
    letterSpacing: '-0.5px',
  },
  pageSubtitle: { color: textSecondary, fontSize: '15px', fontWeight: 500 },
  userInfo: { display: 'flex', alignItems: 'center', gap: '24px' },
  bellIcon: {
    fontSize: '20px',
    color: textSecondary,
    cursor: 'pointer',
    padding: '10px',
    borderRadius: '12px',
    background: 'rgba(0,0,0,0.03)',
  },
  userAvatar: {
    width: '44px',
    height: '44px',
    background: `linear-gradient(135deg, ${accentColor} 0%, #059669 100%)`,
    borderRadius: '14px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 700,
    color: 'white',
    boxShadow: `0 4px 12px ${accentGlow}`,
    border: '2px solid rgba(255, 255, 255, 0.5)',
  },

  // ========== STATS GRID ==========
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: '24px',
    marginBottom: '32px',
  },
  statCard: {
    background: bgCard,
    borderRadius: '20px',
    padding: '24px',
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
    transition: 'all 0.3s ease',
  },
  statIcon: {
    fontSize: '28px',
    color: accentColor,
    background: 'rgba(16, 185, 129, 0.1)',
    width: '56px',
    height: '56px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '14px',
  },
  statNumber: {
    fontSize: '24px',
    fontWeight: 800,
    color: textPrimary,
    margin: 0,
  },
  statLabel: {
    fontSize: '13px',
    color: textSecondary,
    margin: '4px 0 0 0',
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },

  // ========== CARDS ==========
  card: {
    background: bgCard,
    borderRadius: '24px',
    padding: '28px',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    borderBottom: `1px solid ${cardBorder}`,
    paddingBottom: '16px',
    marginBottom: '24px',
  },
  cardTitle: {
    fontSize: '18px',
    fontWeight: 700,
    margin: 0,
    color: textPrimary,
  },

  // ========== DASHBOARD GRID ==========
  dashboardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(450px, 1fr))',
    gap: '24px',
  },

  // ========== PIRÂMIDE ==========
  pyramid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginBottom: '16px',
  },
  pyramidLevel: {
    padding: '14px 18px',
    borderRadius: '12px',
    display: 'flex',
    justifyContent: 'space-between',
    fontWeight: 600,
    fontSize: '13px',
    transition: 'transform 0.2s ease',
  },
  level4: {
    background: 'rgba(239, 68, 68, 0.08)',
    color: '#dc2626',
    border: '1px solid rgba(239, 68, 68, 0.15)',
  },
  level3: {
    background: 'rgba(245, 158, 11, 0.08)',
    color: '#d97706',
    border: '1px solid rgba(245, 158, 11, 0.15)',
  },
  level2: {
    background: 'rgba(59, 130, 246, 0.08)',
    color: '#2563eb',
    border: '1px solid rgba(59, 130, 246, 0.15)',
  },
  level1: {
    background: 'rgba(16, 185, 129, 0.08)',
    color: '#059669',
    border: '1px solid rgba(16, 185, 129, 0.15)',
  },
  cardFooter: {
    borderTop: `1px solid ${cardBorder}`,
    paddingTop: '16px',
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '12px',
    color: textSecondary,
  },

  // ========== INDICADORES ==========
  indicatorsGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '16px',
  },
  indicator: {
    padding: '16px',
    background: 'rgba(0, 0, 0, 0.02)',
    borderRadius: '16px',
    border: `1px solid ${cardBorder}`,
    textAlign: 'center',
  },
  indicatorLabel: {
    fontSize: '11px',
    color: textSecondary,
    display: 'block',
    marginBottom: '8px',
    fontWeight: 600,
    textTransform: 'uppercase',
  },
  indicatorValue: {
    fontSize: '24px',
    fontWeight: 800,
    color: textPrimary,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  trendUp: { fontSize: '11px', color: '#ef4444', fontWeight: 600 },
  trendStable: { fontSize: '11px', color: textSecondary },

  // ========== CASOS ==========
  caseItem: { marginBottom: '16px' },
  caseBar: {
    background: 'rgba(0, 0, 0, 0.05)',
    borderRadius: '10px',
    height: '12px',
    position: 'relative',
    overflow: 'hidden',
    marginTop: '8px',
  },
  caseBarFill: {
    background: accentColor,
    height: '100%',
    borderRadius: '10px',
    boxShadow: `0 0 10px ${accentGlow}`,
  },
  casePercent: {
    position: 'absolute',
    right: '0',
    top: '-20px',
    fontSize: '11px',
    fontWeight: 700,
    color: textSecondary,
  },

  // ========== GRÁFICOS ==========
  chartContainer: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'flex-end',
    height: '200px',
    gap: '20px',
    paddingTop: '20px',
  },
  barContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '12px',
  },
  bar: {
    width: '100%',
    background: `linear-gradient(180deg, ${accentColor} 0%, #059669 100%)`,
    borderRadius: '8px 8px 4px 4px',
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    minHeight: '4px',
    boxShadow: `0 4px 12px ${accentGlow}`,
  },
  barValue: {
    color: 'white',
    fontWeight: 700,
    fontSize: '11px',
    marginTop: '-22px',
  },
  barLabel: { fontSize: '11px', color: textSecondary, fontWeight: 500 },

  // ========== TABELAS ==========
  tableWrapper: { overflowX: 'auto', marginBottom: '16px' },
  dataTable: { width: '100%', borderCollapse: 'collapse' },
  th: {
    padding: '14px 16px',
    textAlign: 'left',
    borderBottom: `2px solid ${cardBorder}`,
    background: 'rgba(0, 0, 0, 0.02)',
    fontWeight: 700,
    color: textPrimary,
    fontSize: '13px',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  td: {
    padding: '14px 16px',
    borderBottom: `1px solid ${cardBorder}`,
    color: textSecondary,
    fontSize: '14px',
  },

  // ========== BOTÕES ==========
  viewReportBtn: {
    background: 'rgba(16, 185, 129, 0.1)',
    border: 'none',
    color: accentColor,
    fontWeight: 700,
    cursor: 'pointer',
    padding: '6px 12px',
    borderRadius: '8px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '12px',
  },

  // ========== FUNCIONARIOS HEADER ==========
  funcionariosHeader: {
    background: bgCard,
    borderRadius: '24px',
    padding: '32px',
    marginBottom: '32px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  funcionariosTitle: {
    fontSize: '24px',
    fontWeight: 800,
    color: textPrimary,
    margin: 0,
    letterSpacing: '-0.5px',
  },
  funcionariosSubtitle: {
    fontSize: '14px',
    color: textSecondary,
    marginTop: '6px',
    fontWeight: 500,
  },

  // ========== BOTÃO ADICIONAR ==========
  addButton: {
    background: `linear-gradient(135deg, ${accentColor} 0%, #059669 100%)`,
    color: 'white',
    border: 'none',
    padding: '14px 28px',
    borderRadius: '14px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontWeight: 700,
    fontSize: '14px',
    boxShadow: `0 8px 15px -3px ${accentGlow}`,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },

  // ========== FORMULÁRIOS ==========
  formCard: {
    background: bgCard,
    borderRadius: '24px',
    padding: '32px',
    marginBottom: '32px',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  formTitle: {
    fontSize: '20px',
    fontWeight: 800,
    color: textPrimary,
    marginBottom: '8px',
  },
  formSubtitle: {
    fontSize: '14px',
    color: textSecondary,
    marginBottom: '32px',
    paddingBottom: '20px',
    borderBottom: `1px solid ${cardBorder}`,
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '24px',
  },
  formGroupFull: { gridColumn: 'span 3' },
  formGroup: { display: 'flex', flexDirection: 'column', gap: '10px' },
  formLabel: {
    fontSize: '12px',
    fontWeight: 700,
    color: textSecondary,
    textTransform: 'uppercase',
    letterSpacing: '1px',
    paddingLeft: '4px',
  },
  formLabelRequired: { color: '#ef4444', marginLeft: '4px' },
  formInput: {
    padding: '14px 18px',
    background: 'rgba(0, 0, 0, 0.02)',
    border: `1px solid ${cardBorder}`,
    borderRadius: '12px',
    fontSize: '15px',
    color: textPrimary,
    outline: 'none',
    transition: 'all 0.3s ease',
  },

  // ========== REGIME BUTTONS ==========
  regimeButtons: { display: 'flex', gap: '12px', marginTop: '4px' },
  regimeBtn: {
    flex: 1,
    padding: '12px 16px',
    border: `1px solid ${cardBorder}`,
    borderRadius: '12px',
    background: 'rgba(0, 0, 0, 0.02)',
    color: textSecondary,
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 600,
    textAlign: 'center',
    transition: 'all 0.3s ease',
  },
  regimeBtnActive: {
    background: 'rgba(16, 185, 129, 0.1)',
    color: accentColor,
    borderColor: accentColor,
    boxShadow: `0 0 10px ${accentGlow}`,
  },

  // ========== BOTÕES FORM ==========
  formButtons: {
    display: 'flex',
    gap: '16px',
    justifyContent: 'flex-end',
    marginTop: '32px',
    paddingTop: '32px',
    borderTop: `1px solid ${cardBorder}`,
    gridColumn: 'span 3',
  },
  saveBtn: {
    background: `linear-gradient(135deg, ${accentColor} 0%, #059669 100%)`,
    color: 'white',
    border: 'none',
    padding: '14px 32px',
    borderRadius: '14px',
    cursor: 'pointer',
    fontWeight: 700,
    fontSize: '14px',
    textTransform: 'uppercase',
    boxShadow: `0 8px 15px -3px ${accentGlow}`,
  },
  cancelBtn: {
    background: 'rgba(0, 0, 0, 0.03)',
    color: textPrimary,
    border: `1px solid ${cardBorder}`,
    padding: '14px 32px',
    borderRadius: '14px',
    cursor: 'pointer',
    fontWeight: 700,
    fontSize: '14px',
    textTransform: 'uppercase',
  },

  // ========== TABELAS ==========
  tableContainer: {
    background: bgCard,
    borderRadius: '24px',
    overflow: 'hidden',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  employeeTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '14px',
  },
  employeeTh: {
    padding: '18px 20px',
    textAlign: 'left',
    borderBottom: `2px solid ${cardBorder}`,
    background: 'rgba(0, 0, 0, 0.02)',
    fontWeight: 700,
    color: textPrimary,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    fontSize: '12px',
  },
  employeeTd: {
    padding: '16px 20px',
    borderBottom: `1px solid ${cardBorder}`,
    color: textSecondary,
  },
  deleteBtn: {
    background: 'rgba(239, 68, 68, 0.08)',
    color: '#dc2626',
    border: 'none',
    padding: '8px 14px',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 700,
    transition: 'all 0.2s ease',
  },

  // ========== BADGES ==========
  regimeBadge: {
    display: 'inline-block',
    padding: '6px 14px',
    borderRadius: '10px',
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
  },
  regimeOffshore: { background: 'rgba(245, 158, 11, 0.08)', color: '#d97706' },
  regimeOnshore: { background: 'rgba(16, 185, 129, 0.08)', color: '#059669' },

  // ========== EMPTY STATE ==========
  noDataCell: {
    textAlign: 'center',
    padding: '80px 20px',
    color: textSecondary,
    fontSize: '15px',
  },

  // ========== STATUS BADGES ==========
  statusBadge: {
    display: 'inline-block',
    padding: '6px 14px',
    borderRadius: '10px',
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
  },
  statusNormal: { background: 'rgba(16, 185, 129, 0.08)', color: '#059669' },
  statusSobrepeso: { background: 'rgba(245, 158, 11, 0.08)', color: '#d97706' },
  statusObesidade: { background: 'rgba(239, 68, 68, 0.08)', color: '#dc2626' },

  // ========== IMC MODULE ==========
  imcContainer: { padding: '32px', background: 'transparent' },
  imcStatsHeader: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '24px',
    marginBottom: '32px',
  },
  imcStatCard: {
    background: bgCard,
    borderRadius: '24px',
    padding: '28px',
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  imcStatIcon: { fontSize: '32px' },
  imcStatValue: { fontSize: '28px', fontWeight: 800, color: textPrimary },
  imcStatLabel: {
    fontSize: '12px',
    color: textSecondary,
    marginTop: '4px',
    fontWeight: 600,
    textTransform: 'uppercase',
  },
  imcMainHeader: {
    background: bgCard,
    borderRadius: '24px',
    padding: '32px',
    marginBottom: '32px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  imcMainTitle: {
    fontSize: '24px',
    fontWeight: 800,
    color: textPrimary,
    margin: 0,
  },
  imcTotalFichas: { textAlign: 'right' },
  imcTotalNumber: {
    fontSize: '48px',
    fontWeight: 900,
    color: accentColor,
    display: 'block',
    lineHeight: 1,
    filter: `drop-shadow(0 0 10px ${accentGlow})`,
  },
  imcTotalLabel: {
    fontSize: '12px',
    color: textSecondary,
    fontWeight: 600,
    textTransform: 'uppercase',
    marginTop: '4px',
  },
  imcChartCard: {
    background: bgCard,
    borderRadius: '24px',
    padding: '32px',
    marginBottom: '32px',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  imcChartTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '24px',
    paddingBottom: '16px',
    borderBottom: `1px solid ${cardBorder}`,
    fontSize: '16px',
    fontWeight: 700,
    color: textPrimary,
  },
  monthlyChartContainer: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'flex-end',
    height: '240px',
    gap: '24px',
    paddingTop: '20px',
  },
  monthBar: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '16px',
  },
  monthBarFill: {
    width: '100%',
    maxWidth: '60px',
    background: `linear-gradient(180deg, ${accentColor} 0%, #059669 100%)`,
    borderRadius: '12px 12px 6px 6px',
    transition: 'height 0.6s cubic-bezier(0.4, 0, 0.2, 1)',
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    position: 'relative',
    boxShadow: `0 4px 15px ${accentGlow}`,
  },
  monthBarValue: {
    color: 'white',
    fontWeight: 800,
    fontSize: '12px',
    marginTop: '-24px',
  },
  monthBarLabel: {
    fontSize: '11px',
    color: textSecondary,
    fontWeight: 600,
    textTransform: 'uppercase',
  },
  imcTableCard: {
    background: bgCard,
    borderRadius: '24px',
    padding: '28px',
    marginBottom: '32px',
    border: `1px solid ${cardBorder}`,
    overflowX: 'auto',
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  imcTableHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
    paddingBottom: '16px',
    borderBottom: `1px solid ${cardBorder}`,
  },
  imcTableHeaderH3: {
    fontSize: '18px',
    fontWeight: 700,
    color: textPrimary,
    margin: 0,
  },
  imcTableInfo: {
    fontSize: '13px',
    color: textSecondary,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontWeight: 500,
  },
  imcDataTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '13px',
  },
  imcDataTableTh: {
    padding: '16px 12px',
    textAlign: 'left',
    background: 'rgba(0, 0, 0, 0.02)',
    fontWeight: 700,
    color: textPrimary,
    borderBottom: `2px solid ${cardBorder}`,
    whiteSpace: 'nowrap',
    textTransform: 'uppercase',
    fontSize: '11px',
    letterSpacing: '0.5px',
  },
  imcDataTableTd: {
    padding: '14px 12px',
    borderBottom: `1px solid ${cardBorder}`,
    whiteSpace: 'nowrap',
    color: textSecondary,
  },
  imcBottomGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '32px',
    marginBottom: '32px',
  },
  imcClassificationCard: {
    background: bgCard,
    borderRadius: '24px',
    padding: '32px',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  imcClassificationCardH4: {
    fontSize: '16px',
    fontWeight: 700,
    color: textPrimary,
    marginBottom: '24px',
    paddingBottom: '12px',
    borderBottom: `1px solid ${cardBorder}`,
  },
  classificationList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  classificationItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 18px',
    background: 'rgba(0, 0, 0, 0.02)',
    borderRadius: '14px',
    border: `1px solid ${cardBorder}`,
  },
  classificationLeft: { display: 'flex', alignItems: 'center', gap: '14px' },
  classDot: { width: '10px', height: '10px', borderRadius: '50%' },
  classificationRight: { display: 'flex', alignItems: 'center', gap: '12px' },
  classCount: { fontSize: '20px', fontWeight: 800, color: textPrimary },
  classPercent: { fontSize: '12px', color: textSecondary, fontWeight: 500 },

  // ========== SEARCH ==========
  searchContainer: {
    background: bgCard,
    borderRadius: '16px',
    padding: '20px 28px',
    marginBottom: '24px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '20px',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  searchBox: {
    display: 'flex',
    alignItems: 'center',
    flex: 1,
    maxWidth: '450px',
    position: 'relative',
  },
  searchIcon: {
    position: 'absolute',
    left: '16px',
    color: textSecondary,
    fontSize: '14px',
  },
  searchInput: {
    width: '100%',
    padding: '12px 16px 12px 45px',
    background: 'rgba(0, 0, 0, 0.02)',
    border: `1px solid ${cardBorder}`,
    borderRadius: '12px',
    fontSize: '14px',
    color: textPrimary,
    outline: 'none',
    transition: 'all 0.3s ease',
  },
  clearSearchBtn: {
    position: 'absolute',
    right: '16px',
    background: 'none',
    border: 'none',
    color: textSecondary,
    cursor: 'pointer',
  },
  resultsCount: { fontSize: '13px', color: textSecondary, fontWeight: 500 },

  // ========== EMPLOYEE SEARCH ==========
  employeeSearchContainer: { position: 'relative', width: '100%' },
  employeeSearchBox: { position: 'relative', width: '100%' },
  employeeSearchIcon: {
    position: 'absolute',
    left: '16px',
    top: '50%',
    transform: 'translateY(-50%)',
    color: textSecondary,
    fontSize: '16px',
  },
  employeeSearchInput: {
    width: '100%',
    padding: '14px 16px 14px 48px',
    background: 'rgba(0, 0, 0, 0.02)',
    border: `1px solid ${cardBorder}`,
    borderRadius: '12px',
    fontSize: '15px',
    color: textPrimary,
    outline: 'none',
  },
  employeeSearchClear: {
    position: 'absolute',
    right: '16px',
    top: '50%',
    transform: 'translateY(-50%)',
    background: 'none',
    border: 'none',
    color: textSecondary,
    cursor: 'pointer',
  },
  employeeDropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    background: bgCard,
    borderRadius: '16px',
    boxShadow: '0 15px 50px rgba(0,0,0,0.15)',
    marginTop: '12px',
    maxHeight: '350px',
    overflowY: 'auto',
    zIndex: 1000,
    border: `1px solid ${cardBorder}`,
  },
  employeeDropdownItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    cursor: 'pointer',
    borderBottom: `1px solid ${cardBorder}`,
    transition: 'background 0.2s ease',
  },
  employeeDropdownCargo: {
    fontSize: '12px',
    color: textSecondary,
    marginTop: '4px',
    fontWeight: 500,
  },
  employeeDropdownIcon: { color: accentColor, fontSize: '14px' },
  employeeDropdownEmpty: {
    padding: '32px',
    textAlign: 'center',
    color: textSecondary,
  },

  // ========== PLACEHOLDER ==========
  placeholderCard: {
    textAlign: 'center',
    padding: '100px 32px',
    background: bgCard,
    borderRadius: '24px',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  placeholderText: {
    fontSize: '22px',
    fontWeight: 800,
    color: textPrimary,
    marginTop: '24px',
  },
  placeholderSubtext: {
    color: textSecondary,
    marginTop: '10px',
    fontSize: '15px',
  },

  // ========== PRESSÃO ARTERIAL ==========
  pressureContainer: { padding: '32px', background: 'transparent' },
  pressureHeader: {
    background: bgCard,
    borderRadius: '24px',
    padding: '32px',
    marginBottom: '32px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  pressureTitle: {
    fontSize: '24px',
    fontWeight: 800,
    color: textPrimary,
    margin: 0,
  },
  pressureSubtitle: {
    fontSize: '14px',
    color: textSecondary,
    marginTop: '6px',
    fontWeight: 500,
  },
  pressureAddButton: {
    background: `linear-gradient(135deg, ${accentColor} 0%, #059669 100%)`,
    color: 'white',
    border: 'none',
    padding: '14px 28px',
    borderRadius: '14px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontWeight: 700,
    fontSize: '14px',
    boxShadow: `0 8px 15px -3px ${accentGlow}`,
  },
  pressureFormCard: {
    background: bgCard,
    borderRadius: '24px',
    padding: '32px',
    marginBottom: '32px',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  pressureFormHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '32px',
    paddingBottom: '16px',
    borderBottom: `1px solid ${cardBorder}`,
  },
  pressureFormIcon: { fontSize: '24px', color: accentColor },
  pressureFormGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '24px',
  },
  pressureFormActions: {
    gridColumn: 'span 3',
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '16px',
    marginTop: '32px',
    paddingTop: '32px',
    borderTop: `1px solid ${cardBorder}`,
  },
  pressureSaveBtn: {
    background: `linear-gradient(135deg, ${accentColor} 0%, #059669 100%)`,
    color: 'white',
    border: 'none',
    padding: '14px 32px',
    borderRadius: '14px',
    cursor: 'pointer',
    fontWeight: 700,
    textTransform: 'uppercase',
  },
  pressureCancelBtn: {
    background: 'rgba(0, 0, 0, 0.03)',
    color: textPrimary,
    border: `1px solid ${cardBorder}`,
    padding: '14px 32px',
    borderRadius: '14px',
    cursor: 'pointer',
    fontWeight: 700,
    textTransform: 'uppercase',
  },
  pressureTableContainer: {
    background: bgCard,
    borderRadius: '24px',
    padding: '24px',
    overflowX: 'auto',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  pressureTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '14px',
  },
  pressureTableTh: {
    padding: '18px 16px',
    textAlign: 'left',
    borderBottom: `2px solid ${cardBorder}`,
    background: 'rgba(0, 0, 0, 0.02)',
    fontWeight: 700,
    color: textPrimary,
    fontSize: '12px',
    textTransform: 'uppercase',
  },
  pressureTableTd: {
    padding: '16px',
    borderBottom: `1px solid ${cardBorder}`,
    color: textSecondary,
  },
  pressureValue: { fontWeight: 800, color: accentColor },
  employeeNameCell: { fontWeight: 700, color: textPrimary },

  // ========== PRÉ-EMBARQUE ==========
  preEmbarqueContainer: { padding: '32px', background: 'transparent' },
  preEmbarqueHeader: {
    background: bgCard,
    borderRadius: '24px',
    padding: '32px',
    marginBottom: '32px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  preEmbarqueTitle: {
    fontSize: '24px',
    fontWeight: 800,
    color: textPrimary,
    margin: 0,
  },
  preEmbarqueSubtitle: {
    fontSize: '14px',
    color: textSecondary,
    marginTop: '6px',
    fontWeight: 500,
  },
  preEmbarqueAddButton: {
    background: `linear-gradient(135deg, ${accentColor} 0%, #059669 100%)`,
    color: 'white',
    border: 'none',
    padding: '14px 28px',
    borderRadius: '14px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontWeight: 700,
    fontSize: '14px',
    boxShadow: `0 8px 15px -3px ${accentGlow}`,
  },
  preEmbarqueFormCard: {
    background: bgCard,
    borderRadius: '24px',
    padding: '32px',
    marginBottom: '32px',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  preEmbarqueFormHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '32px',
    paddingBottom: '16px',
    borderBottom: `1px solid ${cardBorder}`,
  },
  preEmbarqueFormHeaderH3: {
    fontSize: '20px',
    fontWeight: 800,
    color: textPrimary,
    margin: 0,
  },
  preEmbarqueFormGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '24px',
  },
  preEmbarqueFormActions: {
    gridColumn: 'span 3',
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '16px',
    marginTop: '32px',
    paddingTop: '32px',
    borderTop: `1px solid ${cardBorder}`,
  },
  preEmbarqueTableCard: {
    background: bgCard,
    borderRadius: '24px',
    padding: '28px',
    overflowX: 'auto',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  preEmbarqueTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '14px',
  },
  preEmbarqueTh: {
    padding: '18px 16px',
    textAlign: 'left',
    background: 'rgba(0, 0, 0, 0.02)',
    fontWeight: 700,
    color: textPrimary,
    borderBottom: `2px solid ${cardBorder}`,
    fontSize: '12px',
    textTransform: 'uppercase',
  },
  preEmbarqueTd: {
    padding: '16px',
    borderBottom: `1px solid ${cardBorder}`,
    color: textSecondary,
  },
  multipleCheckbox: { display: 'flex', alignItems: 'center', gap: '10px' },
  multipleCheckboxLabel: {
    fontSize: '14px',
    color: textSecondary,
    fontWeight: 600,
  },
  tempListCard: {
    background: 'rgba(0, 0, 0, 0.02)',
    borderRadius: '20px',
    padding: '24px',
    marginBottom: '32px',
    border: `1px solid ${cardBorder}`,
  },
  tempListTitle: {
    fontSize: '15px',
    fontWeight: 700,
    color: textPrimary,
    marginBottom: '20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tempListTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '13px',
  },
  tempListTh: {
    padding: '12px',
    textAlign: 'left',
    background: 'rgba(0, 0, 0, 0.02)',
    fontWeight: 700,
    color: textPrimary,
    fontSize: '11px',
    textTransform: 'uppercase',
  },
  tempListTd: {
    padding: '12px',
    borderBottom: `1px solid ${cardBorder}`,
    color: textSecondary,
  },
  removeBtn: {
    background: 'rgba(239, 68, 68, 0.08)',
    color: '#dc2626',
    border: 'none',
    padding: '6px 12px',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 700,
  },
  confirmBatchBtn: {
    background: accentColor,
    color: 'white',
    border: 'none',
    padding: '10px 20px',
    borderRadius: '10px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 700,
    boxShadow: `0 4px 10px ${accentGlow}`,
  },

  // ========== CONTROLE DE REFEIÇÃO ==========
  refContainer: {
    padding: '32px',
    background: 'transparent',
    minHeight: 'calc(100vh - 120px)',
  },
  refHeader: {
    background: bgCard,
    borderRadius: '24px',
    padding: '32px',
    marginBottom: '32px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  refTitle: {
    fontSize: '24px',
    fontWeight: 800,
    color: textPrimary,
    margin: 0,
  },
  refSubtitle: {
    fontSize: '14px',
    color: textSecondary,
    marginTop: '6px',
    fontWeight: 500,
  },
  refAddButton: {
    background: `linear-gradient(135deg, ${accentColor} 0%, #059669 100%)`,
    color: 'white',
    border: 'none',
    padding: '14px 28px',
    borderRadius: '14px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontWeight: 700,
    fontSize: '14px',
    boxShadow: `0 8px 15px -3px ${accentGlow}`,
  },
  monthSelector: {
    background: bgCard,
    borderRadius: '24px',
    padding: '28px',
    marginBottom: '32px',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  monthSelectorHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '20px',
    paddingBottom: '16px',
    borderBottom: `1px solid ${cardBorder}`,
    fontSize: '15px',
    fontWeight: 700,
    color: textPrimary,
  },
  monthGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(6, 1fr)',
    gap: '14px',
  },
  monthButton: {
    padding: '14px 16px',
    background: 'rgba(0, 0, 0, 0.02)',
    border: `1px solid ${cardBorder}`,
    borderRadius: '14px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 600,
    color: textSecondary,
    transition: 'all 0.3s ease',
    textAlign: 'center',
  },
  monthButtonActive: {
    background: 'rgba(16, 185, 129, 0.1)',
    color: accentColor,
    borderColor: accentColor,
    boxShadow: `0 0 10px ${accentGlow}`,
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.6)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modalContent: {
    background: bgCard,
    borderRadius: '32px',
    width: '550px',
    maxWidth: '90%',
    boxShadow: '0 25px 80px rgba(0, 0, 0, 0.3)',
    border: `1px solid ${cardBorder}`,
    overflow: 'hidden',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '28px 32px',
    borderBottom: `1px solid ${cardBorder}`,
    background: 'rgba(0, 0, 0, 0.02)',
  },
  modalClose: {
    background: 'rgba(0, 0, 0, 0.03)',
    border: 'none',
    width: '36px',
    height: '36px',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    color: textSecondary,
    fontSize: '18px',
  },
  modalBody: { padding: '32px' },
  dropZone: {
    border: `2px dashed ${cardBorder}`,
    borderRadius: '24px',
    padding: '50px 32px',
    textAlign: 'center',
    transition: 'all 0.3s ease',
    cursor: 'pointer',
    background: 'rgba(0, 0, 0, 0.01)',
  },
  dropZoneActive: { borderColor: accentColor, background: accentGlow },
  dropZoneIcon: {
    fontSize: '56px',
    color: accentColor,
    marginBottom: '20px',
    filter: `drop-shadow(0 0 10px ${accentGlow})`,
  },
  dropZoneSubtext: {
    color: textSecondary,
    margin: '12px 0',
    fontSize: '14px',
    fontWeight: 500,
  },
  dropZoneLabel: {
    background: accentColor,
    color: 'white',
    padding: '12px 28px',
    borderRadius: '12px',
    cursor: 'pointer',
    display: 'inline-block',
    marginTop: '12px',
    fontWeight: 700,
    fontSize: '14px',
    textTransform: 'uppercase',
  },
  fileInput: { display: 'none' },
  dropZoneInfo: {
    fontSize: '11px',
    color: textSecondary,
    marginTop: '20px',
    fontWeight: 500,
  },
  refFileList: {
    background: bgCard,
    borderRadius: '24px',
    padding: '28px',
    marginBottom: '32px',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  fileListHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
    paddingBottom: '16px',
    borderBottom: `1px solid ${cardBorder}`,
  },
  fileCount: {
    fontSize: '12px',
    color: accentColor,
    background: 'rgba(16, 185, 129, 0.1)',
    padding: '6px 14px',
    borderRadius: '20px',
    fontWeight: 700,
  },
  emptyFiles: {
    textAlign: 'center',
    padding: '80px 32px',
    color: textSecondary,
  },
  emptyIcon: {
    fontSize: '72px',
    color: 'rgba(0, 0, 0, 0.05)',
    marginBottom: '20px',
  },
  emptyButton: {
    background: 'none',
    border: `1px solid ${accentColor}`,
    color: accentColor,
    padding: '10px 24px',
    borderRadius: '12px',
    cursor: 'pointer',
    marginTop: '20px',
    fontWeight: 700,
    fontSize: '14px',
    transition: 'all 0.3s ease',
  },
  filesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
    gap: '20px',
  },
  fileCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    padding: '20px',
    background: 'rgba(0, 0, 0, 0.02)',
    borderRadius: '18px',
    border: `1px solid ${cardBorder}`,
    transition: 'all 0.3s ease',
  },
  fileIcon: { flexShrink: 0, fontSize: '24px', color: accentColor },
  fileInfo: { flex: 1, minWidth: 0 },
  fileName: {
    fontWeight: 700,
    color: textPrimary,
    marginBottom: '6px',
    fontSize: '14px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  fileMeta: {
    fontSize: '11px',
    color: textSecondary,
    display: 'flex',
    gap: '10px',
    alignItems: 'center',
    fontWeight: 600,
  },
  fileActions: { display: 'flex', gap: '10px' },
  fileActionBtn: {
    background: 'rgba(16, 185, 129, 0.1)',
    color: accentColor,
    border: 'none',
    width: '36px',
    height: '36px',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    textDecoration: 'none',
    transition: 'all 0.2s ease',
  },
  fileActionDelete: {
    background: 'rgba(239, 68, 68, 0.1)',
    color: '#dc2626',
    border: 'none',
    width: '36px',
    height: '36px',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  refSummary: {
    background: bgCard,
    borderRadius: '24px',
    padding: '28px',
    border: `1px solid ${cardBorder}`,
    boxShadow: '0 4px 15px rgba(0, 0, 0, 0.06)',
  },
  summaryHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '24px',
    paddingBottom: '16px',
    borderBottom: `1px solid ${cardBorder}`,
    fontSize: '15px',
    fontWeight: 700,
    color: textPrimary,
  },
  summaryStats: {
    display: 'grid',
    gridTemplateColumns: 'repeat(6, 1fr)',
    gap: '20px',
  },
  summaryCard: {
    textAlign: 'center',
    padding: '16px',
    background: 'rgba(0, 0, 0, 0.02)',
    borderRadius: '16px',
    border: `1px solid ${cardBorder}`,
  },
  summaryMonth: {
    fontSize: '11px',
    fontWeight: 700,
    color: textSecondary,
    marginBottom: '10px',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  summaryCount: { fontSize: '24px', fontWeight: 800, color: accentColor },
  summaryBar: {
    height: '6px',
    background: 'rgba(0, 0, 0, 0.05)',
    borderRadius: '100px',
    marginTop: '12px',
    overflow: 'hidden',
  },
  summaryBarFill: {
    height: '100%',
    background: accentColor,
    borderRadius: '100px',
    transition: 'width 0.8s cubic-bezier(0.4, 0, 0.2, 1)',
    boxShadow: `0 0 8px ${accentGlow}`,
  },
};
